server:
  port: 8080
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: myvm
    username: root
    password: root
    publisher-confirms: true
    listener:
      simple:
        prefetch: 3
